### ISSUE TITLE
Webjar path to css and js don't work

### ISSUE THREAD

**Issue by fantomst** [xitrum-framework/xitrum-new#17] opened 2018-03-02 14:53 UTC
Please fix webjar path in xitrum-new  project and other example projects.

**Comment by ngocdaothanh** [comment] 2018-03-02 15:43
Hi I've tried running the latest version of xitrum-new. The static files in webjars (https://github.com/xitrum-framework/xitrum-new/blob/master/src/main/scalate/quickstart/action/DefaultLayout.jade) can be loaded expected.

Can you explain in more details what doesn't work for you?

**Comment by fantomst** [comment] 2018-03-03 15:41
I'm launching xitrum-new-master from zip archive downloaded from the website and project started normaly, but css and js resources:
http://127.0.0.1:8000/webjars/bootstrap-css/3.3.6/css/bootstrap.css
http://127.0.0.1:8000/webjars/xitrum/3.28.8/xitrum.css
return 404 error

**Comment by ngocdaothanh** [comment] 2018-03-23 10:52
I could not reproduce the problem on Mac and Linux.

What OS are you using? Can you try on other machines?

**Comment by ngocdaothanh** [comment] 2019-02-14 00:12
Closing this issue as I cannot reproduce the problem, and there's no more info for a long time.

**Closed by ngocdaothanh** 2019-02-14 00:12 UTC
